/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HorarioDto } from './horarioDto';

export interface PagoDto {
  descripcion?: string;
  horario?: HorarioDto;
  id?: number;
  idHorario?: number;
  total?: number;
}
