/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PagoDto } from './pagoDto';
import type { UsuarioDto } from './usuarioDto';

export interface PagoRequest {
  idUsuario?: number;
  pagador?: boolean;
  pagoDto?: PagoDto;
  usuariosImplicados?: UsuarioDto[];
}
