/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UsuarioDto } from './usuarioDto';

export interface PagoDetalleDto {
  id?: number;
  idPagador?: number;
  total?: number;
  usuarios?: UsuarioDto[];
}
