/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HorarioDto } from './horarioDto';
import type { UsuarioDto } from './usuarioDto';

export interface PagoDetalleDto {
  descripcion?: string;
  horario?: HorarioDto;
  id?: number;
  idPagador?: number;
  total?: number;
  usuarios?: UsuarioDto[];
}
