/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HorarioDto } from './horarioDto';
import type { UbicacionDto } from './ubicacionDto';

export interface PlanDto {
  descripcion?: string;
  horario?: HorarioDto;
  id?: number;
  idHorario?: number;
  idUbicacion?: number;
  idViaje?: number;
  importancia?: number;
  nombre?: string;
  ubicacion?: UbicacionDto;
}
