/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlanDto {
  descripcion?: string;
  id?: number;
  idHorario?: number;
  idPago?: number;
  idUbicacion?: number;
  idViaje?: number;
  importancia?: number;
  nombre?: string;
}
