/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PropuestaDto {
  descripcion?: string;
  ganadora?: boolean;
  id?: number;
  idViaje?: number;
  nombre?: string;
  presupuesto?: number;
  valoracion?: number;
}
