/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterUserDto {
  email?: string;
  fullName?: string;
  password?: string;
}
