/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TicketDto {
  asiento?: string;
  documento?: string[];
  id?: number;
  idPlan?: number;
  nombre?: string;
  qr?: string;
}
