/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UbicacionDto {
  coordenadas?: string;
  direccion?: string;
  esExterior?: boolean;
  id?: number;
  requisitos?: string[];
  tipoVestimenta?: string;
}
