/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GrantedAuthority } from './grantedAuthority';

export interface UsuarioDto {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: GrantedAuthority[];
  createdAt?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  id?: number;
  pagador?: boolean;
  password?: string;
  updatedAt?: string;
  username?: string;
}
