/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HorarioDto } from './horarioDto';
import type { PlanDetalleDto } from './planDetalleDto';
import type { PropuestaDto } from './propuestaDto';

export interface ViajeDetalleDto {
  emailParticipantes?: string[];
  horario?: HorarioDto;
  id?: number;
  planes?: PlanDetalleDto[];
  propuestas?: PropuestaDto[];
  titulo?: string;
}
