/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpHeaders,
  HttpParams,
} from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { UbicacionDto } from '../../model';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]:
          | string
          | number
          | boolean
          | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class UbicacionControllerService {
  constructor(private http: HttpClient) {}
  getUbicacion<TData = UbicacionDto>(
    id: number,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.get<TData>(`/ubicaciones/${id}`, options);
  }
  updateUbicacion<TData = void>(
    id: number,
    ubicacionDto: UbicacionDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.put<TData>(`/ubicaciones/${id}`, ubicacionDto, options);
  }
  deleteUbicacion<TData = void>(
    id: number,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.delete<TData>(`/ubicaciones/${id}`, options);
  }
  getUbicaciones<TData = UbicacionDto[]>(
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.get<TData>(`/ubicaciones`, options);
  }
  createUbicacion<TData = number>(
    ubicacionDto: UbicacionDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.post<TData>(`/ubicaciones`, ubicacionDto, options);
  }
}

export type GetUbicacionClientResult = NonNullable<UbicacionDto>;
export type UpdateUbicacionClientResult = NonNullable<void>;
export type DeleteUbicacionClientResult = NonNullable<void>;
export type GetUbicacionesClientResult = NonNullable<UbicacionDto[]>;
export type CreateUbicacionClientResult = NonNullable<number>;
