/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpHeaders,
  HttpParams,
} from '@angular/common/http';
import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import type {
  LoginResponse,
  LoginUserDto,
  RegisterUserDto,
  UsuarioDto,
} from '../../model';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]:
          | string
          | number
          | boolean
          | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class AuthenticationControllerService {
  constructor(private http: HttpClient) {}
  register<TData = UsuarioDto>(
    registerUserDto: RegisterUserDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.post<TData>(`/auth/signup`, registerUserDto, options);
  }
  authenticate<TData = LoginResponse>(
    loginUserDto: LoginUserDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.post<TData>(`/auth/login`, loginUserDto, options);
  }
  private tokenSubject: BehaviorSubject<string | null> = new BehaviorSubject<string | null>(localStorage.getItem('access_token'));

  getToken(): Observable<string | null> {
    return this.tokenSubject.asObservable();
  }

  setToken(token: string): void {
    localStorage.setItem('access_token', token);
    this.tokenSubject.next(token);
  }

  clearToken(): void {
    localStorage.removeItem('access_token');
    this.tokenSubject.next(null);
  }

}

export type RegisterClientResult = NonNullable<UsuarioDto>;
export type AuthenticateClientResult = NonNullable<LoginResponse>;
