/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpHeaders,
  HttpParams,
} from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  LoginResponse,
  LoginUserDto,
  RegisterUserDto,
  UsuarioDto,
} from '../../model';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]:
          | string
          | number
          | boolean
          | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class AuthenticationControllerService {
  constructor(private http: HttpClient) {}
  register<TData = UsuarioDto>(
    registerUserDto: RegisterUserDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.post<TData>(`/api/auth/signup`, registerUserDto, options);
  }
  authenticate<TData = LoginResponse>(
    loginUserDto: LoginUserDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.post<TData>(`/api/auth/login`, loginUserDto, options);
  }
}

export type RegisterClientResult = NonNullable<UsuarioDto>;
export type AuthenticateClientResult = NonNullable<LoginResponse>;
