/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpHeaders,
  HttpParams,
} from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { PropuestaDto } from '../../model';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]:
          | string
          | number
          | boolean
          | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class PropuestaControllerService {
  constructor(private http: HttpClient) {}
  getPropuesta<TData = PropuestaDto>(
    id: number,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.get<TData>(`/api/propuestas/${id}`, options);
  }
  updatePropuesta<TData = void>(
    id: number,
    propuestaDto: PropuestaDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.put<TData>(`/api/propuestas/${id}`, propuestaDto, options);
  }
  deletePropuesta<TData = void>(
    id: number,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.delete<TData>(`/api/propuestas/${id}`, options);
  }
  getPropuestas<TData = PropuestaDto[]>(
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.get<TData>(`/api/propuestas`, options);
  }
  createPropuesta<TData = number>(
    propuestaDto: PropuestaDto,
    options?: HttpClientOptions,
  ): Observable<TData> {
    return this.http.post<TData>(`/api/propuestas`, propuestaDto, options);
  }
}

export type GetPropuestaClientResult = NonNullable<PropuestaDto>;
export type UpdatePropuestaClientResult = NonNullable<void>;
export type DeletePropuestaClientResult = NonNullable<void>;
export type GetPropuestasClientResult = NonNullable<PropuestaDto[]>;
export type CreatePropuestaClientResult = NonNullable<number>;
