name: Angular CI
on:
  push:
    branches:
      - main
      - '*-*[0-9]'
  pull_request:
    branches:
      - main
      - '*-*[0-9]'
jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: {fetch-depth: 0}
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
      working-directory: "./TripPlanner/"
    - name: Build
      run: npm run build --prod
      working-directory: "./TripPlanner/"
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: "./TripPlanner/"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Slack WebHook
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: 'repo,author,commit,author,workflow'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
